#!/usr/bin/env bash

git clone git://github.com/tovrleaf/vim-files.git ~/.vim

echo source ~/.vim/vimrc.vim >> ~/.vimrc
echo source ~/.vim/gvimrc.vim >> ~/.gvimrc

. ~/.vim/bin/install.sh

# Neovim

ln -s ~/.vim ~/.config/nvim
ln -s ~/.vimrc ~/.config/nvim/init.vim

# Fonts

./bundle/fonts/install.sh
