#!/usr/bin/env bash

git clone git://github.com/tovrleaf/vim-files.git ~/.vim-git

echo source ~/.vim-git/vimrc.vim >> ~/.vimrc
echo source ~/.vim-git/gvimrc.vim >> ~/.gvimrc

$HOME/.vim-git/bin/install.sh
